$ErrorActionPreference = "Stop"
$path = "D:\\optiflow\\src\\pages\\consulta\\AtendimentoPage.tsx"
$stamp = Get-Date -Format "yyyyMMdd_HHmmss"
$backup = "$path.bak_$stamp"
Copy-Item $path $backup
Write-Host "Backup criado em $backup"

$bytes = [System.IO.File]::ReadAllBytes($path)
$hasBom = ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF)
$rawContent = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)

$hadCRLF = $rawContent.Contains("`r`n")
$content = $rawContent -replace "`r`n", "`n"

# --- Bloco 1 ---
$old1 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('aW1wb3J0IHsKICBFeWUsIENsaXBib2FyZExpc3QsIEZpbGVUZXh0LCBDaGV2cm9uRG93biwgQ2hldnJvblVwLAogIFNhdmUsIFByaW50ZXIsIEFycm93TGVmdCwgQ2hlY2tDaXJjbGUsIFVzZXIsIEhpc3RvcnksIFNob3BwaW5nQmFnCn0gZnJvbSAnbHVjaWRlLXJlYWN0Jzs='))
$new1 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('aW1wb3J0IHsKICBFeWUsIENsaXBib2FyZExpc3QsIEZpbGVUZXh0LCBDaGV2cm9uRG93biwgQ2hldnJvblVwLAogIFNhdmUsIFByaW50ZXIsIEFycm93TGVmdCwgQ2hlY2tDaXJjbGUsIFVzZXIsIEhpc3RvcnksIFNob3BwaW5nQmFnLAogIFBhcGVyY2xpcCwgVXBsb2FkCn0gZnJvbSAnbHVjaWRlLXJlYWN0Jzs='))
if ($content.IndexOf($old1) -lt 0) { throw "Bloco 1 nao encontrado no arquivo - patch abortado, nada foi alterado." }
$content = $content.Replace($old1, $new1)

# --- Bloco 2 ---
$old2 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('dHlwZSBTZWN0aW9uID0KICB8ICdwcmVzY3JpY2FvX29jdWxvcycgfCAncHJlc2NyaWNhb19sYycgfCAnYW5hbW5lc2UnCiAgfCAnYXRlc3RhZG9zJyB8ICdhanVzdGVzJzs='))
$new2 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('dHlwZSBTZWN0aW9uID0KICB8ICdwcmVzY3JpY2FvX29jdWxvcycgfCAncHJlc2NyaWNhb19sYycgfCAnYW5hbW5lc2UnCiAgfCAnYXRlc3RhZG9zJyB8ICdhbmV4b3MnIHwgJ2FqdXN0ZXMnOw=='))
if ($content.IndexOf($old2) -lt 0) { throw "Bloco 2 nao encontrado no arquivo - patch abortado, nada foi alterado." }
$content = $content.Replace($old2, $new2)

# --- Bloco 3 ---
$old3 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICAgIHsgaWQ6ICdhdGVzdGFkb3MnLCBsYWJlbDogJ0F0ZXN0YWRvcyBlIERvY3VtZW50b3MnIH0sCiAgICB7IGlkOiAnYWp1c3RlcycsIGxhYmVsOiAnQWp1c3RlcycgfSwKICBdOw=='))
$new3 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICAgIHsgaWQ6ICdhdGVzdGFkb3MnLCBsYWJlbDogJ0F0ZXN0YWRvcyBlIERvY3VtZW50b3MnIH0sCiAgICB7IGlkOiAnYW5leG9zJywgbGFiZWw6ICdBbmV4b3MnIH0sCiAgICB7IGlkOiAnYWp1c3RlcycsIGxhYmVsOiAnQWp1c3RlcycgfSwKICBdOw=='))
if ($content.IndexOf($old3) -lt 0) { throw "Bloco 3 nao encontrado no arquivo - patch abortado, nada foi alterado." }
$content = $content.Replace($old3, $new3)

# --- Bloco 4 ---
$old4 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICBjb25zdCBbcGFydG5lcnNoaXBzLCBzZXRQYXJ0bmVyc2hpcHNdID0gdXNlU3RhdGU8YW55W10+KFtdKTsKICBjb25zdCBbcGFydG5lcnNoaXBJZCwgc2V0UGFydG5lcnNoaXBJZF0gPSB1c2VTdGF0ZSgnJyk7'))
$new4 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICBjb25zdCBbcGFydG5lcnNoaXBzLCBzZXRQYXJ0bmVyc2hpcHNdID0gdXNlU3RhdGU8YW55W10+KFtdKTsKICBjb25zdCBbcGFydG5lcnNoaXBJZCwgc2V0UGFydG5lcnNoaXBJZF0gPSB1c2VTdGF0ZSgnJyk7CiAgY29uc3QgW2FuZXhvcywgc2V0QW5leG9zXSA9IHVzZVN0YXRlPGFueVtdPihbXSk7CiAgY29uc3QgW3VwbG9hZGluZ0FuZXhvLCBzZXRVcGxvYWRpbmdBbmV4b10gPSB1c2VTdGF0ZShmYWxzZSk7'))
if ($content.IndexOf($old4) -lt 0) { throw "Bloco 4 nao encontrado no arquivo - patch abortado, nada foi alterado." }
$content = $content.Replace($old4, $new4)

# --- Bloco 5 ---
$old5 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICAgICAgaWYgKGRhdGEucGFydG5lcnNoaXBfaWQpIHNldFBhcnRuZXJzaGlwSWQoZGF0YS5wYXJ0bmVyc2hpcF9pZCk7CiAgICAgIGlmIChkYXRhLnZhbG9yX2NvYnJhZG8gIT0gbnVsbCkgewogICAgICAgIHNldERvY1ZhbG9yRXhhbWUoU3RyaW5nKE51bWJlcihkYXRhLnZhbG9yX2NvYnJhZG8pLnRvRml4ZWQoMikpLnJlcGxhY2UoJy4nLCAnLCcpKTsKICAgICAgfSBlbHNlIGlmIChkYXRhLnByb2NlZHVyZV9pZCkgewogICAgICAgIGNvbnN0IHsgZGF0YTogcHJvYyB9ID0gYXdhaXQgc3VwYWJhc2UuZnJvbSgncHJvY2VkdXJlcycpLnNlbGVjdCgnZGVmYXVsdF9wcmljZScpLmVxKCdpZCcsIGRhdGEucHJvY2VkdXJlX2lkKS5tYXliZVNpbmdsZSgpOwogICAgICAgIGlmIChwcm9jPy5kZWZhdWx0X3ByaWNlICE9IG51bGwpIHNldERvY1ZhbG9yRXhhbWUoU3RyaW5nKE51bWJlcihwcm9jLmRlZmF1bHRfcHJpY2UpLnRvRml4ZWQoMikpLnJlcGxhY2UoJy4nLCAnLCcpKTsKICAgICAgfQogICAgICBzZXRMb2FkaW5nKGZhbHNlKTsKICAgIH07CiAgICBsb2FkKCk7CiAgfSwgW2lkLCB0ZW5hbnRJZF0pOw=='))
$new5 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICAgICAgaWYgKGRhdGEucGFydG5lcnNoaXBfaWQpIHNldFBhcnRuZXJzaGlwSWQoZGF0YS5wYXJ0bmVyc2hpcF9pZCk7CiAgICAgIGlmIChkYXRhLnZhbG9yX2NvYnJhZG8gIT0gbnVsbCkgewogICAgICAgIHNldERvY1ZhbG9yRXhhbWUoU3RyaW5nKE51bWJlcihkYXRhLnZhbG9yX2NvYnJhZG8pLnRvRml4ZWQoMikpLnJlcGxhY2UoJy4nLCAnLCcpKTsKICAgICAgfSBlbHNlIGlmIChkYXRhLnByb2NlZHVyZV9pZCkgewogICAgICAgIGNvbnN0IHsgZGF0YTogcHJvYyB9ID0gYXdhaXQgc3VwYWJhc2UuZnJvbSgncHJvY2VkdXJlcycpLnNlbGVjdCgnZGVmYXVsdF9wcmljZScpLmVxKCdpZCcsIGRhdGEucHJvY2VkdXJlX2lkKS5tYXliZVNpbmdsZSgpOwogICAgICAgIGlmIChwcm9jPy5kZWZhdWx0X3ByaWNlICE9IG51bGwpIHNldERvY1ZhbG9yRXhhbWUoU3RyaW5nKE51bWJlcihwcm9jLmRlZmF1bHRfcHJpY2UpLnRvRml4ZWQoMikpLnJlcGxhY2UoJy4nLCAnLCcpKTsKICAgICAgfQogICAgICBjb25zdCB7IGRhdGE6IGFuZXhvc0RhdGEgfSA9IGF3YWl0IHN1cGFiYXNlLmZyb20oJ2N1c3RvbWVyX2F0dGFjaG1lbnRzJykKICAgICAgICAuc2VsZWN0KCdpZCxmaWxlX25hbWUsZmlsZV9wYXRoLGNyZWF0ZWRfYXQnKS5lcSgnY29uc3VsdGF0aW9uX2lkJywgaWQpLm9yZGVyKCdjcmVhdGVkX2F0JywgeyBhc2NlbmRpbmc6IGZhbHNlIH0pOwogICAgICBzZXRBbmV4b3MoYW5leG9zRGF0YSB8fCBbXSk7CiAgICAgIHNldExvYWRpbmcoZmFsc2UpOwogICAgfTsKICAgIGxvYWQoKTsKICB9LCBbaWQsIHRlbmFudElkXSk7CgogIGNvbnN0IGhhbmRsZVVwbG9hZEFuZXhvID0gYXN5bmMgKGZpbGU6IEZpbGUpID0+IHsKICAgIGlmICghdGVuYW50SWQgfHwgIWNvbnN1bHRhdGlvbikgcmV0dXJuOwogICAgc2V0VXBsb2FkaW5nQW5leG8odHJ1ZSk7CiAgICB0cnkgewogICAgICBjb25zdCBzYWZlTmFtZSA9IGZpbGUubmFtZS5yZXBsYWNlKC9bXmEtekEtWjAtOS5fLV0vZywgJ18nKTsKICAgICAgY29uc3QgcGF0aCA9IGByZWNlaXRhcy8ke2NvbnN1bHRhdGlvbi5jdXN0b21lcl9pZH0vJHtEYXRlLm5vdygpfV8ke3NhZmVOYW1lfWA7CiAgICAgIGNvbnN0IHsgZXJyb3I6IHVwRXJyIH0gPSBhd2FpdCBzdXBhYmFzZS5zdG9yYWdlLmZyb20oJ2F0dGFjaG1lbnRzJykudXBsb2FkKHBhdGgsIGZpbGUpOwogICAgICBpZiAodXBFcnIpIHRocm93IHVwRXJyOwogICAgICBjb25zdCB7IGVycm9yOiBpbnNFcnIgfSA9IGF3YWl0IHN1cGFiYXNlLmZyb20oJ2N1c3RvbWVyX2F0dGFjaG1lbnRzJykuaW5zZXJ0KFt7CiAgICAgICAgdGVuYW50X2lkOiB0ZW5hbnRJZCwgY3VzdG9tZXJfaWQ6IGNvbnN1bHRhdGlvbi5jdXN0b21lcl9pZCwgY29uc3VsdGF0aW9uX2lkOiBpZCwKICAgICAgICBmaWxlX25hbWU6IGZpbGUubmFtZSwgZmlsZV9wYXRoOiBwYXRoLAogICAgICB9XSk7CiAgICAgIGlmIChpbnNFcnIpIHRocm93IGluc0VycjsKICAgICAgdG9hc3Quc3VjY2VzcygnQXJxdWl2byBhbmV4YWRvIScpOwogICAgICBjb25zdCB7IGRhdGE6IGFuZXhvc0RhdGEgfSA9IGF3YWl0IHN1cGFiYXNlLmZyb20oJ2N1c3RvbWVyX2F0dGFjaG1lbnRzJykKICAgICAgICAuc2VsZWN0KCdpZCxmaWxlX25hbWUsZmlsZV9wYXRoLGNyZWF0ZWRfYXQnKS5lcSgnY29uc3VsdGF0aW9uX2lkJywgaWQpLm9yZGVyKCdjcmVhdGVkX2F0JywgeyBhc2NlbmRpbmc6IGZhbHNlIH0pOwogICAgICBzZXRBbmV4b3MoYW5leG9zRGF0YSB8fCBbXSk7CiAgICB9IGNhdGNoIChlOiBhbnkpIHsKICAgICAgdG9hc3QuZXJyb3IoZS5tZXNzYWdlIHx8ICdFcnJvIGFvIGFuZXhhciBhcnF1aXZvJyk7CiAgICB9IGZpbmFsbHkgewogICAgICBzZXRVcGxvYWRpbmdBbmV4byhmYWxzZSk7CiAgICB9CiAgfTsKCiAgY29uc3QgYWJyaXJBbmV4b0F0ZW5kaW1lbnRvID0gYXN5bmMgKGE6IGFueSkgPT4gewogICAgY29uc3QgeyBkYXRhIH0gPSBhd2FpdCBzdXBhYmFzZS5zdG9yYWdlLmZyb20oJ2F0dGFjaG1lbnRzJykuY3JlYXRlU2lnbmVkVXJsKGEuZmlsZV9wYXRoLCA2MCk7CiAgICBpZiAoZGF0YT8uc2lnbmVkVXJsKSB3aW5kb3cub3BlbihkYXRhLnNpZ25lZFVybCwgJ19ibGFuaycpOwogICAgZWxzZSB0b2FzdC5lcnJvcignTsOjbyBmb2kgcG9zc8OtdmVsIGFicmlyIG8gYXJxdWl2bycpOwogIH07'))
if ($content.IndexOf($old5) -lt 0) { throw "Bloco 5 nao encontrado no arquivo - patch abortado, nada foi alterado." }
$content = $content.Replace($old5, $new5)

# --- Bloco 6 ---
$old6 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICAgICAgICAgIHsvKiDilZDilZAgQUpVU1RFUyDilZDilZAgKi99CiAgICAgICAgICB7c2VjdGlvbiA9PT0gJ2FqdXN0ZXMnICYmICg='))
$new6 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICAgICAgICAgIHsvKiDilZDilZAgQU5FWE9TIOKVkOKVkCAqL30KICAgICAgICAgIHtzZWN0aW9uID09PSAnYW5leG9zJyAmJiAoCiAgICAgICAgICAgIDxkaXYgc3R5bGU9e3sgcGFkZGluZzogJzIwcHgnIH19PgogICAgICAgICAgICAgIDxoMyBzdHlsZT17eyBtYXJnaW46ICcwIDAgMTZweCcsIGZvbnRTaXplOiAxNSB9fT5BbmV4b3MgZGVzdGUgYXRlbmRpbWVudG88L2gzPgogICAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJjYXJkIiBzdHlsZT17eyBwYWRkaW5nOiAxOCB9fT4KICAgICAgICAgICAgICAgIDxkaXYgc3R5bGU9e3sgZGlzcGxheTogJ2ZsZXgnLCBnYXA6IDEwLCBmbGV4V3JhcDogJ3dyYXAnIH19PgogICAgICAgICAgICAgICAgICB7YW5leG9zLmxlbmd0aCA9PT0gMCAmJiAoCiAgICAgICAgICAgICAgICAgICAgPGRpdiBzdHlsZT17eyBmb250U2l6ZTogMTMsIGNvbG9yOiAndmFyKC0tdGV4dC1tdXRlZCknIH19Pk5lbmh1bSBhbmV4byBhaW5kYS48L2Rpdj4KICAgICAgICAgICAgICAgICAgKX0KICAgICAgICAgICAgICAgICAge2FuZXhvcy5tYXAoYSA9PiAoCiAgICAgICAgICAgICAgICAgICAgPGRpdiBrZXk9e2EuaWR9IG9uQ2xpY2s9eygpID0+IGFicmlyQW5leG9BdGVuZGltZW50byhhKX0gc3R5bGU9e3sgZGlzcGxheTogJ2ZsZXgnLCBhbGlnbkl0ZW1zOiAnY2VudGVyJywgZ2FwOiA2LCBiYWNrZ3JvdW5kOiAncmdiYSgyNTUsMjU1LDI1NSwuMDQpJywgYm9yZGVyOiAnMXB4IHNvbGlkIHZhcigtLWJvcmRlciknLCBib3JkZXJSYWRpdXM6IDgsIHBhZGRpbmc6ICc4cHggMTJweCcsIGZvbnRTaXplOiAxMiwgY3Vyc29yOiAncG9pbnRlcicgfX0+CiAgICAgICAgICAgICAgICAgICAgICA8UGFwZXJjbGlwIHNpemU9ezEzfSAvPiB7YS5maWxlX25hbWV9CiAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICkpfQogICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICA8bGFiZWwgc3R5bGU9e3sgZGlzcGxheTogJ2lubGluZS1mbGV4JywgYWxpZ25JdGVtczogJ2NlbnRlcicsIGdhcDogNiwgYmFja2dyb3VuZDogJ25vbmUnLCBib3JkZXI6ICcxcHggZGFzaGVkIHZhcigtLWJvcmRlciknLCBjb2xvcjogJyM4MThjZjgnLCBib3JkZXJSYWRpdXM6IDgsIHBhZGRpbmc6ICc4cHggMTJweCcsIGZvbnRTaXplOiAxMiwgY3Vyc29yOiAncG9pbnRlcicsIG1hcmdpblRvcDogMTIgfX0+CiAgICAgICAgICAgICAgICAgIDxVcGxvYWQgc2l6ZT17MTN9IC8+IHt1cGxvYWRpbmdBbmV4byA/ICdFbnZpYW5kby4uLicgOiAnQW5leGFyIGFycXVpdm8nfQogICAgICAgICAgICAgICAgICA8aW5wdXQgdHlwZT0iZmlsZSIgYWNjZXB0PSJpbWFnZS8qLC5wZGYiIHN0eWxlPXt7IGRpc3BsYXk6ICdub25lJyB9fSBkaXNhYmxlZD17dXBsb2FkaW5nQW5leG99CiAgICAgICAgICAgICAgICAgICAgb25DaGFuZ2U9e2UgPT4geyBpZiAoZS50YXJnZXQuZmlsZXM/LlswXSkgaGFuZGxlVXBsb2FkQW5leG8oZS50YXJnZXQuZmlsZXNbMF0pOyB9fSAvPgogICAgICAgICAgICAgICAgPC9sYWJlbD4KICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICApfQoKICAgICAgICAgIHsvKiDilZDilZAgQUpVU1RFUyDilZDilZAgKi99CiAgICAgICAgICB7c2VjdGlvbiA9PT0gJ2FqdXN0ZXMnICYmICg='))
if ($content.IndexOf($old6) -lt 0) { throw "Bloco 6 nao encontrado no arquivo - patch abortado, nada foi alterado." }
$content = $content.Replace($old6, $new6)

if ($hadCRLF) { $content = $content -replace "`n", "`r`n" }

if ($hasBom) {
  $utf8Bom = New-Object System.Text.UTF8Encoding($true)
  [System.IO.File]::WriteAllText($path, $content, $utf8Bom)
} else {
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($path, $content, $utf8NoBom)
}

Write-Host "AtendimentoPage.tsx atualizado: nova secao Anexos, vinculada ao atendimento especifico (nao so ao paciente)."
Write-Host "Rode: npm run build"