$ErrorActionPreference = "Stop"
$path = "D:\\optiflow\\src\\pages\\consulta\\AtendimentoPage.tsx"
$stamp = Get-Date -Format "yyyyMMdd_HHmmss"
$backup = "$path.bak_$stamp"
Copy-Item $path $backup
Write-Host "Backup criado em $backup"

$bytes = [System.IO.File]::ReadAllBytes($path)
$hasBom = ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF)
$rawContent = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)

$hadCRLF = $rawContent.Contains("`r`n")
$content = $rawContent -replace "`r`n", "`n"

# --- Bloco 1 ---
$old1 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICAvLyDilIDilIAgc2FsdmFyIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAogIGNvbnN0IGhhbmRsZVNhdmUgPSBhc3luYyAoKSA9PiB7'))
$new1 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICAvLyDilIDilIAgRmFzZSA2OiBsYW7Dp2FtZW50b3MgZmluYW5jZWlyb3MgYXV0b23DoXRpY29zIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAogIGNvbnN0IHN5bmNMYW5jYW1lbnRvc0ZpbmFuY2Vpcm9zID0gYXN5bmMgKGNvbnN1bHRhdGlvbklkOiBzdHJpbmcpID0+IHsKICAgIC8vIElkZW1wb3RlbnRlOiBzZW1wcmUgbGltcGEgb3MgbGFuw6dhbWVudG9zIGFudGlnb3MgZGVzdGEgY29uc3VsdGEgYW50ZXMgZGUKICAgIC8vIHJlY3JpYXIsIGFzc2ltIHNhbHZhciBkZSBub3ZvIChleDogY29ycmlnaW5kbyB2YWxvcikgbsOjbyBkdXBsaWNhIG5hZGEuCiAgICBhd2FpdCBzdXBhYmFzZS5mcm9tKCdjbGluaWNfZmluYW5jaWFsX2VudHJpZXMnKS5kZWxldGUoKS5lcSgnY29uc3VsdGF0aW9uX2lkJywgY29uc3VsdGF0aW9uSWQpOwoKICAgIGNvbnN0IHZhbG9yID0gbnVtKGRvY1ZhbG9yRXhhbWUpOwogICAgaWYgKHZhbG9yID09IG51bGwgfHwgdmFsb3IgPD0gMCB8fCBzdGF0dXMgIT09ICdyZWFsaXphZGEnKSByZXR1cm47CgogICAgY29uc3QgZW50cmllczogYW55W10gPSBbewogICAgICB0ZW5hbnRfaWQ6IHRlbmFudElkLCB0eXBlOiAncmVjZWl0YScsIGNhdGVnb3J5OiAnY29uc3VsdGEnLAogICAgICBkZXNjcmlwdGlvbjogJ1JlY2VpdGEgZGUgYXRlbmRpbWVudG8nLCBhbW91bnQ6IHZhbG9yLAogICAgICBkdWVfZGF0ZTogZGF0ZSB8fCBudWxsLCBzdGF0dXM6ICdwZW5kZW50ZScsCiAgICAgIGNvbnN1bHRhdGlvbl9pZDogY29uc3VsdGF0aW9uSWQsIHBhcnRuZXJzaGlwX2lkOiBwYXJ0bmVyc2hpcElkIHx8IG51bGwsCiAgICAgIHByb2NlZHVyZV9pZDogY29uc3VsdGF0aW9uPy5wcm9jZWR1cmVfaWQgfHwgbnVsbCwKICAgIH1dOwoKICAgIGlmIChwYXJ0bmVyc2hpcElkKSB7CiAgICAgIGNvbnN0IHBhcnRuZXIgPSBwYXJ0bmVyc2hpcHMuZmluZChwID0+IHAuaWQgPT09IHBhcnRuZXJzaGlwSWQpOwogICAgICBpZiAocGFydG5lcj8uY29tbWlzc2lvbl9wZXJjZW50KSB7CiAgICAgICAgZW50cmllcy5wdXNoKHsKICAgICAgICAgIHRlbmFudF9pZDogdGVuYW50SWQsIHR5cGU6ICdkZXNwZXNhJywgY2F0ZWdvcnk6ICdjb21pc3Nhb19jb252ZW5pbycsCiAgICAgICAgICBkZXNjcmlwdGlvbjogJ0NvbWlzc8OjbyBkbyBjb252w6puaW8nLCBhbW91bnQ6IHZhbG9yICogcGFydG5lci5jb21taXNzaW9uX3BlcmNlbnQgLyAxMDAsCiAgICAgICAgICBkdWVfZGF0ZTogZGF0ZSB8fCBudWxsLCBzdGF0dXM6ICdwZW5kZW50ZScsCiAgICAgICAgICBjb25zdWx0YXRpb25faWQ6IGNvbnN1bHRhdGlvbklkLCBwYXJ0bmVyc2hpcF9pZDogcGFydG5lcnNoaXBJZCwKICAgICAgICB9KTsKICAgICAgfQogICAgfQoKICAgIGNvbnN0IHByb2ZJZCA9IGNvbnN1bHRhdGlvbj8ucHJvZmVzc2lvbmFsX2lkOwogICAgaWYgKHByb2ZJZCkgewogICAgICBjb25zdCB7IGRhdGE6IHByb2YgfSA9IGF3YWl0IHN1cGFiYXNlLmZyb20oJ3Byb2Zlc3Npb25hbHMnKS5zZWxlY3QoJ3RpcG9fcGFnYW1lbnRvLHZhbG9yX2ZpeG8scGVyY2VudHVhbF9jb21pc3NhbycpLmVxKCdpZCcsIHByb2ZJZCkubWF5YmVTaW5nbGUoKTsKICAgICAgaWYgKHByb2Y/LnRpcG9fcGFnYW1lbnRvID09PSAnZml4bycgJiYgcHJvZi52YWxvcl9maXhvKSB7CiAgICAgICAgZW50cmllcy5wdXNoKHsKICAgICAgICAgIHRlbmFudF9pZDogdGVuYW50SWQsIHR5cGU6ICdkZXNwZXNhJywgY2F0ZWdvcnk6ICdjb21pc3Nhb19wcm9maXNzaW9uYWwnLAogICAgICAgICAgZGVzY3JpcHRpb246ICdDb21pc3PDo28gZG8gcHJvZmlzc2lvbmFsIChmaXhvKScsIGFtb3VudDogcHJvZi52YWxvcl9maXhvLAogICAgICAgICAgZHVlX2RhdGU6IGRhdGUgfHwgbnVsbCwgc3RhdHVzOiAncGVuZGVudGUnLAogICAgICAgICAgY29uc3VsdGF0aW9uX2lkOiBjb25zdWx0YXRpb25JZCwgcHJvZmVzc2lvbmFsX2lkOiBwcm9mSWQsCiAgICAgICAgfSk7CiAgICAgIH0gZWxzZSBpZiAocHJvZj8udGlwb19wYWdhbWVudG8gPT09ICdjb21pc3NhbycgJiYgcHJvZi5wZXJjZW50dWFsX2NvbWlzc2FvKSB7CiAgICAgICAgZW50cmllcy5wdXNoKHsKICAgICAgICAgIHRlbmFudF9pZDogdGVuYW50SWQsIHR5cGU6ICdkZXNwZXNhJywgY2F0ZWdvcnk6ICdjb21pc3Nhb19wcm9maXNzaW9uYWwnLAogICAgICAgICAgZGVzY3JpcHRpb246ICdDb21pc3PDo28gZG8gcHJvZmlzc2lvbmFsJywgYW1vdW50OiB2YWxvciAqIHByb2YucGVyY2VudHVhbF9jb21pc3NhbyAvIDEwMCwKICAgICAgICAgIGR1ZV9kYXRlOiBkYXRlIHx8IG51bGwsIHN0YXR1czogJ3BlbmRlbnRlJywKICAgICAgICAgIGNvbnN1bHRhdGlvbl9pZDogY29uc3VsdGF0aW9uSWQsIHByb2Zlc3Npb25hbF9pZDogcHJvZklkLAogICAgICAgIH0pOwogICAgICB9CiAgICB9CgogICAgYXdhaXQgc3VwYWJhc2UuZnJvbSgnY2xpbmljX2ZpbmFuY2lhbF9lbnRyaWVzJykuaW5zZXJ0KGVudHJpZXMpOwogIH07CgogIC8vIOKUgOKUgCBzYWx2YXIg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACiAgY29uc3QgaGFuZGxlU2F2ZSA9IGFzeW5jICgpID0+IHs='))
if ($content.IndexOf($old1) -lt 0) { throw "Bloco 1 nao encontrado no arquivo - patch abortado, nada foi alterado." }
$content = $content.Replace($old1, $new1)

# --- Bloco 2 ---
$old2 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICAgICAgY29uc3QgeyBlcnJvciB9ID0gYXdhaXQgc3VwYWJhc2UuZnJvbSgnY29uc3VsdGF0aW9ucycpLnVwZGF0ZShwYXlsb2FkKS5lcSgnaWQnLCBpZCk7CiAgICAgIGlmIChlcnJvcikgdGhyb3cgZXJyb3I7CiAgICAgIHRvYXN0LnN1Y2Nlc3MoJ1NhbHZvIGNvbSBzdWNlc3NvIScpOw=='))
$new2 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICAgICAgY29uc3QgeyBlcnJvciB9ID0gYXdhaXQgc3VwYWJhc2UuZnJvbSgnY29uc3VsdGF0aW9ucycpLnVwZGF0ZShwYXlsb2FkKS5lcSgnaWQnLCBpZCk7CiAgICAgIGlmIChlcnJvcikgdGhyb3cgZXJyb3I7CiAgICAgIGF3YWl0IHN5bmNMYW5jYW1lbnRvc0ZpbmFuY2Vpcm9zKGlkKTsKICAgICAgdG9hc3Quc3VjY2VzcygnU2Fsdm8gY29tIHN1Y2Vzc28hJyk7'))
if ($content.IndexOf($old2) -lt 0) { throw "Bloco 2 nao encontrado no arquivo - patch abortado, nada foi alterado." }
$content = $content.Replace($old2, $new2)

if ($hadCRLF) { $content = $content -replace "`n", "`r`n" }

if ($hasBom) {
  $utf8Bom = New-Object System.Text.UTF8Encoding($true)
  [System.IO.File]::WriteAllText($path, $content, $utf8Bom)
} else {
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($path, $content, $utf8NoBom)
}

Write-Host "AtendimentoPage.tsx atualizado: ao salvar com status realizada e valor preenchido, gera automaticamente os lancamentos em clinic_financial_entries (receita + comissoes, quando configuradas)."
Write-Host "Rode: npm run build"