$ErrorActionPreference = "Stop"
$path = "D:\\optiflow\\src\\pages\\CadastrosPage.tsx"
$stamp = Get-Date -Format "yyyyMMdd_HHmmss"
$backup = "$path.bak_$stamp"
Copy-Item $path $backup
Write-Host "Backup criado em $backup"

$bytes = [System.IO.File]::ReadAllBytes($path)
$hasBom = ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF)
$rawContent = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)

$hadCRLF = $rawContent.Contains("`r`n")
$content = $rawContent -replace "`r`n", "`n"

# --- Bloco 1 ---
$old1 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('aW50ZXJmYWNlIFByb2Zlc3Npb25hbCB7CiAgaWQ6IHN0cmluZzsgdGVuYW50X2lkOiBzdHJpbmc7IG5hbWU6IHN0cmluZzsgY3JvPzogc3RyaW5nOwogIHNwZWNpYWx0eT86IHN0cmluZzsgcGhvbmU/OiBzdHJpbmc7IGVtYWlsPzogc3RyaW5nOyBhY3RpdmU6IGJvb2xlYW47IGNyZWF0ZWRfYXQ6IHN0cmluZzsKICBmdW5jaW9uYXJpb19pZD86IHN0cmluZyB8IG51bGw7IGNvbnNlbGhvX251bWVybz86IHN0cmluZzsgY29uc2VsaG9fdWY/OiBzdHJpbmc7CiAgZm90b191cmw/OiBzdHJpbmc7IGFzc2luYXR1cmFfdXJsPzogc3RyaW5nOwp9'))
$new1 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('aW50ZXJmYWNlIFByb2Zlc3Npb25hbCB7CiAgaWQ6IHN0cmluZzsgdGVuYW50X2lkOiBzdHJpbmc7IG5hbWU6IHN0cmluZzsgY3JvPzogc3RyaW5nOwogIHNwZWNpYWx0eT86IHN0cmluZzsgcGhvbmU/OiBzdHJpbmc7IGVtYWlsPzogc3RyaW5nOyBhY3RpdmU6IGJvb2xlYW47IGNyZWF0ZWRfYXQ6IHN0cmluZzsKICBmdW5jaW9uYXJpb19pZD86IHN0cmluZyB8IG51bGw7IGNvbnNlbGhvX251bWVybz86IHN0cmluZzsgY29uc2VsaG9fdWY/OiBzdHJpbmc7CiAgZm90b191cmw/OiBzdHJpbmc7IGFzc2luYXR1cmFfdXJsPzogc3RyaW5nOwogIHRpcG9fcGFnYW1lbnRvPzogc3RyaW5nIHwgbnVsbDsgdmFsb3JfZml4bz86IG51bWJlciB8IG51bGw7IHBlcmNlbnR1YWxfY29taXNzYW8/OiBudW1iZXIgfCBudWxsOwp9'))
if ($content.IndexOf($old1) -lt 0) { throw "Bloco 1 nao encontrado no arquivo - patch abortado, nada foi alterado." }
$content = $content.Replace($old1, $new1)

# --- Bloco 2 ---
$old2 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ZnVuY3Rpb24gZW1wdHlQcm9mRm9ybSgpIHsKICByZXR1cm4gewogICAgbmFtZTonJywgY3JvOicnLCBzcGVjaWFsdHk6J09wdG9tZXRyaWEnLCBwaG9uZTonJywgZW1haWw6JycsCiAgICBjb25zZWxob19udW1lcm86JycsIGNvbnNlbGhvX3VmOicnLCBmb3RvX3VybDonJywgYXNzaW5hdHVyYV91cmw6JycsCiAgICBsb2dpbl9lbWFpbDonJywgbG9naW5fc2VuaGE6JycsCiAgfTsKfQ=='))
$new2 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ZnVuY3Rpb24gZW1wdHlQcm9mRm9ybSgpIHsKICByZXR1cm4gewogICAgbmFtZTonJywgY3JvOicnLCBzcGVjaWFsdHk6J09wdG9tZXRyaWEnLCBwaG9uZTonJywgZW1haWw6JycsCiAgICBjb25zZWxob19udW1lcm86JycsIGNvbnNlbGhvX3VmOicnLCBmb3RvX3VybDonJywgYXNzaW5hdHVyYV91cmw6JycsCiAgICBsb2dpbl9lbWFpbDonJywgbG9naW5fc2VuaGE6JycsCiAgICB0aXBvX3BhZ2FtZW50bzonJywgdmFsb3JfZml4bzpudWxsIGFzIG51bWJlciB8IG51bGwsIHBlcmNlbnR1YWxfY29taXNzYW86bnVsbCBhcyBudW1iZXIgfCBudWxsLAogIH07Cn0='))
if ($content.IndexOf($old2) -lt 0) { throw "Bloco 2 nao encontrado no arquivo - patch abortado, nada foi alterado." }
$content = $content.Replace($old2, $new2)

# --- Bloco 3 ---
$old3 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICAgIHNldFByb2ZGb3JtKHsKICAgICAgbmFtZTpwLm5hbWUsIGNybzpwLmNyb3x8JycsIHNwZWNpYWx0eTpwLnNwZWNpYWx0eXx8J09wdG9tZXRyaWEnLCBwaG9uZTpwLnBob25lfHwnJywgZW1haWw6cC5lbWFpbHx8JycsCiAgICAgIGNvbnNlbGhvX251bWVybzpwLmNvbnNlbGhvX251bWVyb3x8JycsIGNvbnNlbGhvX3VmOnAuY29uc2VsaG9fdWZ8fCcnLAogICAgICBmb3RvX3VybDpwLmZvdG9fdXJsfHwnJywgYXNzaW5hdHVyYV91cmw6cC5hc3NpbmF0dXJhX3VybHx8JycsCiAgICAgIGxvZ2luX2VtYWlsOicnLCBsb2dpbl9zZW5oYTonJywKICAgIH0pOw=='))
$new3 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICAgIHNldFByb2ZGb3JtKHsKICAgICAgbmFtZTpwLm5hbWUsIGNybzpwLmNyb3x8JycsIHNwZWNpYWx0eTpwLnNwZWNpYWx0eXx8J09wdG9tZXRyaWEnLCBwaG9uZTpwLnBob25lfHwnJywgZW1haWw6cC5lbWFpbHx8JycsCiAgICAgIGNvbnNlbGhvX251bWVybzpwLmNvbnNlbGhvX251bWVyb3x8JycsIGNvbnNlbGhvX3VmOnAuY29uc2VsaG9fdWZ8fCcnLAogICAgICBmb3RvX3VybDpwLmZvdG9fdXJsfHwnJywgYXNzaW5hdHVyYV91cmw6cC5hc3NpbmF0dXJhX3VybHx8JycsCiAgICAgIGxvZ2luX2VtYWlsOicnLCBsb2dpbl9zZW5oYTonJywKICAgICAgdGlwb19wYWdhbWVudG86cC50aXBvX3BhZ2FtZW50b3x8JycsIHZhbG9yX2ZpeG86cC52YWxvcl9maXhvID8/IG51bGwsIHBlcmNlbnR1YWxfY29taXNzYW86cC5wZXJjZW50dWFsX2NvbWlzc2FvID8/IG51bGwsCiAgICB9KTs='))
if ($content.IndexOf($old3) -lt 0) { throw "Bloco 3 nao encontrado no arquivo - patch abortado, nada foi alterado." }
$content = $content.Replace($old3, $new3)

# --- Bloco 4 ---
$old4 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICAgICAgY29uc3QgcGF5bG9hZCA9IHsKICAgICAgICBuYW1lOiBwcm9mRm9ybS5uYW1lLCBjcm86IHByb2ZGb3JtLmNybywgc3BlY2lhbHR5OiBwcm9mRm9ybS5zcGVjaWFsdHksCiAgICAgICAgcGhvbmU6IHByb2ZGb3JtLnBob25lLCBlbWFpbDogcHJvZkZvcm0uZW1haWwsCiAgICAgICAgY29uc2VsaG9fbnVtZXJvOiBwcm9mRm9ybS5jb25zZWxob19udW1lcm8sIGNvbnNlbGhvX3VmOiBwcm9mRm9ybS5jb25zZWxob191ZiwKICAgICAgICBmb3RvX3VybDogcHJvZkZvcm0uZm90b191cmwsIGFzc2luYXR1cmFfdXJsOiBwcm9mRm9ybS5hc3NpbmF0dXJhX3VybCwKICAgICAgICBmdW5jaW9uYXJpb19pZDogZnVuY2lvbmFyaW9JZCwKICAgICAgICB0ZW5hbnRfaWQ6IHRlbmFudElkLCBhY3RpdmU6IHRydWUsCiAgICAgIH07'))
$new4 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICAgICAgY29uc3QgcGF5bG9hZCA9IHsKICAgICAgICBuYW1lOiBwcm9mRm9ybS5uYW1lLCBjcm86IHByb2ZGb3JtLmNybywgc3BlY2lhbHR5OiBwcm9mRm9ybS5zcGVjaWFsdHksCiAgICAgICAgcGhvbmU6IHByb2ZGb3JtLnBob25lLCBlbWFpbDogcHJvZkZvcm0uZW1haWwsCiAgICAgICAgY29uc2VsaG9fbnVtZXJvOiBwcm9mRm9ybS5jb25zZWxob19udW1lcm8sIGNvbnNlbGhvX3VmOiBwcm9mRm9ybS5jb25zZWxob191ZiwKICAgICAgICBmb3RvX3VybDogcHJvZkZvcm0uZm90b191cmwsIGFzc2luYXR1cmFfdXJsOiBwcm9mRm9ybS5hc3NpbmF0dXJhX3VybCwKICAgICAgICBmdW5jaW9uYXJpb19pZDogZnVuY2lvbmFyaW9JZCwKICAgICAgICB0aXBvX3BhZ2FtZW50bzogcHJvZkZvcm0udGlwb19wYWdhbWVudG8gfHwgbnVsbCwKICAgICAgICB2YWxvcl9maXhvOiBwcm9mRm9ybS50aXBvX3BhZ2FtZW50byA9PT0gJ2ZpeG8nID8gcHJvZkZvcm0udmFsb3JfZml4byA6IG51bGwsCiAgICAgICAgcGVyY2VudHVhbF9jb21pc3NhbzogcHJvZkZvcm0udGlwb19wYWdhbWVudG8gPT09ICdjb21pc3NhbycgPyBwcm9mRm9ybS5wZXJjZW50dWFsX2NvbWlzc2FvIDogbnVsbCwKICAgICAgICB0ZW5hbnRfaWQ6IHRlbmFudElkLCBhY3RpdmU6IHRydWUsCiAgICAgIH07'))
if ($content.IndexOf($old4) -lt 0) { throw "Bloco 4 nao encontrado no arquivo - patch abortado, nada foi alterado." }
$content = $content.Replace($old4, $new4)

# --- Bloco 5 ---
$old5 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICAgICAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgICAgPGxhYmVsIGNsYXNzTmFtZT0iZm9ybS1sYWJlbCI+U2VuaGEge3Byb2ZMb2dpbkF0dWFsID8gJyhkZWl4ZSBlbSBicmFuY28gcGFyYSBtYW50ZXIpJyA6ICcnfTwvbGFiZWw+CiAgICAgICAgICAgICAgICAgICAgICA8aW5wdXQgY2xhc3NOYW1lPSJmb3JtLWlucHV0IiB0eXBlPSJwYXNzd29yZCIgdmFsdWU9e3Byb2ZGb3JtLmxvZ2luX3NlbmhhfSBvbkNoYW5nZT17ZT0+c2V0UCgnbG9naW5fc2VuaGEnLGUudGFyZ2V0LnZhbHVlKX0gcGxhY2Vob2xkZXI9IlNlbmhhIHBhcmEgbG9naW4iLz4KICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ibW9kYWwtZm9vdGVyIj4='))
$new5 = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ICAgICAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgICAgPGxhYmVsIGNsYXNzTmFtZT0iZm9ybS1sYWJlbCI+U2VuaGEge3Byb2ZMb2dpbkF0dWFsID8gJyhkZWl4ZSBlbSBicmFuY28gcGFyYSBtYW50ZXIpJyA6ICcnfTwvbGFiZWw+CiAgICAgICAgICAgICAgICAgICAgICA8aW5wdXQgY2xhc3NOYW1lPSJmb3JtLWlucHV0IiB0eXBlPSJwYXNzd29yZCIgdmFsdWU9e3Byb2ZGb3JtLmxvZ2luX3NlbmhhfSBvbkNoYW5nZT17ZT0+c2V0UCgnbG9naW5fc2VuaGEnLGUudGFyZ2V0LnZhbHVlKX0gcGxhY2Vob2xkZXI9IlNlbmhhIHBhcmEgbG9naW4iLz4KICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgIDxkaXYgc3R5bGU9e3tib3JkZXJUb3A6JzFweCBzb2xpZCB2YXIoLS1ib3JkZXIpJyxwYWRkaW5nVG9wOjE0LG1hcmdpblRvcDoxNH19PgogICAgICAgICAgICAgICAgICA8ZGl2IHN0eWxlPXt7Zm9udFNpemU6MTIsY29sb3I6J3ZhcigtLXRleHQtbXV0ZWQpJyxtYXJnaW5Cb3R0b206MTB9fT4KICAgICAgICAgICAgICAgICAgICBBY2VydG8gZmluYW5jZWlybyBwb3IgYXRlbmRpbWVudG8gKHVzYWRvIG5vIGxhbsOnYW1lbnRvIGF1dG9tw6F0aWNvIGRhIEZhc2UgNikKICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgIDxkaXYgc3R5bGU9e3tkaXNwbGF5OidncmlkJyxncmlkVGVtcGxhdGVDb2x1bW5zOicxZnIgMWZyJyxnYXA6MTJ9fT4KICAgICAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgICAgPGxhYmVsIGNsYXNzTmFtZT0iZm9ybS1sYWJlbCI+Rm9ybWEgZGUgcGFnYW1lbnRvPC9sYWJlbD4KICAgICAgICAgICAgICAgICAgICAgIDxzZWxlY3QgY2xhc3NOYW1lPSJmb3JtLWlucHV0IiB2YWx1ZT17cHJvZkZvcm0udGlwb19wYWdhbWVudG99IG9uQ2hhbmdlPXtlPT5zZXRQKCd0aXBvX3BhZ2FtZW50bycsIGUudGFyZ2V0LnZhbHVlKX0+CiAgICAgICAgICAgICAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9IiI+TmVuaHVtIChuw6NvIGdlcmEgY29taXNzw6NvKTwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJmaXhvIj5WYWxvciBmaXhvIHBvciBhdGVuZGltZW50bzwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJjb21pc3NhbyI+Q29taXNzw6NvICglKTwvb3B0aW9uPgogICAgICAgICAgICAgICAgICAgICAgPC9zZWxlY3Q+CiAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICAge3Byb2ZGb3JtLnRpcG9fcGFnYW1lbnRvID09PSAnZml4bycgJiYgKAogICAgICAgICAgICAgICAgICAgICAgPGRpdj4KICAgICAgICAgICAgICAgICAgICAgICAgPGxhYmVsIGNsYXNzTmFtZT0iZm9ybS1sYWJlbCI+VmFsb3IgZml4byAoUiQpPC9sYWJlbD4KICAgICAgICAgICAgICAgICAgICAgICAgPGlucHV0IGNsYXNzTmFtZT0iZm9ybS1pbnB1dCIgdHlwZT0ibnVtYmVyIiBzdGVwPSIwLjAxIiB2YWx1ZT17cHJvZkZvcm0udmFsb3JfZml4byA/PyAnJ30KICAgICAgICAgICAgICAgICAgICAgICAgICBvbkNoYW5nZT17ZT0+c2V0UCgndmFsb3JfZml4bycsIGUudGFyZ2V0LnZhbHVlID09PSAnJyA/IG51bGwgOiBwYXJzZUZsb2F0KGUudGFyZ2V0LnZhbHVlKSl9IHBsYWNlaG9sZGVyPSIwLjAwIi8+CiAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICApfQogICAgICAgICAgICAgICAgICAgIHtwcm9mRm9ybS50aXBvX3BhZ2FtZW50byA9PT0gJ2NvbWlzc2FvJyAmJiAoCiAgICAgICAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgICAgICA8bGFiZWwgY2xhc3NOYW1lPSJmb3JtLWxhYmVsIj5QZXJjZW50dWFsIGRlIGNvbWlzc8OjbyAoJSk8L2xhYmVsPgogICAgICAgICAgICAgICAgICAgICAgICA8aW5wdXQgY2xhc3NOYW1lPSJmb3JtLWlucHV0IiB0eXBlPSJudW1iZXIiIHN0ZXA9IjAuMDEiIHZhbHVlPXtwcm9mRm9ybS5wZXJjZW50dWFsX2NvbWlzc2FvID8/ICcnfQogICAgICAgICAgICAgICAgICAgICAgICAgIG9uQ2hhbmdlPXtlPT5zZXRQKCdwZXJjZW50dWFsX2NvbWlzc2FvJywgZS50YXJnZXQudmFsdWUgPT09ICcnID8gbnVsbCA6IHBhcnNlRmxvYXQoZS50YXJnZXQudmFsdWUpKX0gcGxhY2Vob2xkZXI9IjAuMDAiLz4KICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgICl9CiAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9Im1vZGFsLWZvb3RlciI+'))
if ($content.IndexOf($old5) -lt 0) { throw "Bloco 5 nao encontrado no arquivo - patch abortado, nada foi alterado." }
$content = $content.Replace($old5, $new5)

if ($hadCRLF) { $content = $content -replace "`n", "`r`n" }

if ($hasBom) {
  $utf8Bom = New-Object System.Text.UTF8Encoding($true)
  [System.IO.File]::WriteAllText($path, $content, $utf8Bom)
} else {
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($path, $content, $utf8NoBom)
}

Write-Host "CadastrosPage.tsx atualizado: forma de pagamento do profissional (fixo/comissao) agora e configuravel no cadastro."
Write-Host "Rode: npm run build"